### PR TITLE
[ci] Updated github actions workflow to run lint job using ktlint

### LINKED ISSUE #186: [ci] Run ktlint on CI runs
We have ktlint to ensure the code style in the code base stays consistent. There is a ktlint.jar inside the /assets folder which can be used to run ktlint. This should be automated through GitHub actions.

### PR DESCRIPTION
**Pull request by asadmansr**
Hey, I have updated the github actions workflow to include a lint job that will run ktlint analysis using the jar in the assets folders as reference by this issue: https://github.com/vexelabs/bitbuilder/issues/186

### CODE REVIEW

**Comment by asadmansr** [comment]
The CI is performing all of the checks successfully, however the ktlint lint analysis has found some lint issues with source code. Feel free to let me know how to proceed next. Thank you

**Comment by junlarsen** [comment]
Great, thank you for the contribution

I ran ktlint myself and pushed it to your remote so everything should be good to go. I'll merge this later today.

**Comment by asadmansr** [comment]
Hi @supergrecko, thank you merging in the changes. I'm currently participating in the Hacktoberfest event and I would like this PR to be counted as one my contributions. Would you be able to add the hacktoberfest-accepted label to this PR? Thank you

Reference:
"Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR."

**Comment by junlarsen** [comment]
I'll update it and remove the label once hacktoberfest is over

**Comment by asadmansr** [comment]
Thank you @supergrecko! This means a lot. Currently my PR is under the 14-day review period before it get counted. It would be nice if you could leave the topic until Nov 8. If that's not possible, you can just label this PR as `hacktoberfest-accepted`. [You can find more information here](https://hacktoberfest.digitalocean.com/hacktoberfest-update). Thank you so much

**Pull request merged**
